server:
  port: 8080
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    url: jdbc:mysql://srv3.sanjiang.info:3306/mytest?failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: sjes
    password: sjes
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: select 1
    type: com.alibaba.druid.pool.DruidDataSource
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: wjl.test.mybatis.model
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

